apiVersion: ipam.metal3.io/v1alpha1
kind: IPClaim
metadata:
  name: ${IPCLAIM_NAME}
  annotations:
    prow.k8s.io/build-id: "${BUILD_ID}"
    prow.k8s.io/job: "${JOB_NAME}"
spec:
  pool:
    name: capv-e2e-ippool
